[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/PyHuangCs"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "email"
    name       = "邮箱"
    url        = "mailto:pyhuang@mail.ustc.edu.cn"

    [social.params]
        icon = "messages"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about"
    weight     = 1

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives"
    weight     = 2

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search"
    weight     = 3
